// packages/web-ds-angular/src/app/button/button.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

// Angular port of @statrys/web-ds's Button (React). Only the Rec (labeled)
// shape is ported for this pilot — Square/Circle (icon-only) intentionally
// left out, since the point here is proving the token/CSS layer carries over
// unchanged, not re-doing every prop on day one.
export type ButtonVariant = 'primary' | 'secondary' | 'tertiary';
export type ButtonSize = 'sm' | 'md' | 'lg';
export type ButtonShape = 'rec' | 'rounded';

@Component({
  selector: 'ds-button',
  standalone: true,
  templateUrl: './button.component.html',
  styleUrl: './button.component.css',
})
export class ButtonComponent {
  @Input() variant: ButtonVariant = 'primary';
  @Input() size: ButtonSize = 'md';
  @Input() shape: ButtonShape = 'rec';
  @Input() disabled = false;
  @Input() inverse = false;
  @Output() pressed = new EventEmitter<void>();

  get classes(): string {
    return [
      'base',
      this.variant,
      this.size,
      this.shape === 'rounded' ? 'rounded' : null,
      this.inverse ? 'inverse' : null,
    ]
      .filter((c): c is string => !!c)
      .join(' ');
  }

  onClick(): void {
    if (!this.disabled) {
      this.pressed.emit();
    }
  }
}

<button [class]="classes" [disabled]="disabled" (click)="onClick()">
  <ng-content></ng-content>
</button>

// packages/web-ds/src/button/Button.tsx
import React from "react";
import styles from "./Button.module.css";

type ButtonBaseProps = {
  variant?: "primary" | "secondary" | "tertiary";
  size?: "sm" | "md" | "lg";
  disabled?: boolean;
  /** Dark-surface variant — cream fill / cream outline / cream text (Figma "Inverse"). Not available for Shape=Square/Circle — Figma has no inverse icon-only variants. */
  inverse?: boolean;
  onClick?: () => void;
};

type ButtonRecProps = ButtonBaseProps & {
  /** Figma Shape=Rec (default) or Rounded — a labeled button. */
  shape?: "rec" | "rounded";
  children: React.ReactNode;
};

type ButtonIconProps = ButtonBaseProps & {
  /** Figma Shape=Square or Circle — an icon-only button, no label. */
  shape: "square" | "circle";
  icon: React.ReactNode;
  "aria-label": string;
};

export type ButtonProps = ButtonRecProps | ButtonIconProps;

function isIconShape(props: ButtonProps): props is ButtonIconProps {
  return props.shape === "square" || props.shape === "circle";
}

export function Button(props: ButtonProps) {
  const { variant = "primary", size = "md", disabled = false, inverse = false, onClick } = props;
  const shape = props.shape ?? "rec";

  const className = [styles.base, styles[variant], styles[size], styles[shape], inverse && styles.inverse]
    .filter(Boolean)
    .join(" ");

  if (isIconShape(props)) {
    return (
      <button className={className} disabled={disabled} onClick={onClick} aria-label={props["aria-label"]}>
        {props.icon}
      </button>
    );
  }

  return (
    <button className={className} disabled={disabled} onClick={onClick}>
      {props.children}
    </button>
  );
}
