// apps/web-playground/src/App.tsx
import { Button } from "@statrys/web-ds";

const VARIANTS = ["primary", "secondary", "ghost"] as const;
const SIZES = ["sm", "md", "lg"] as const;

export function App() {
  return (
    <div style={{ padding: 32, display: "flex", flexDirection: "column", gap: 24 }}>
      <h1>Core DS Playground — Button (web-ds)</h1>
      {VARIANTS.map((variant) => (
        <div key={variant} style={{ display: "flex", gap: 12, alignItems: "center" }}>
          {SIZES.map((size) => (
            <Button key={size} variant={variant} size={size}>
              {variant} / {size}
            </Button>
          ))}
          <Button variant={variant} disabled>
            disabled
          </Button>
        </div>
      ))}
    </div>
  );
}

// packages/web-ds-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { ButtonComponent, ButtonVariant } from './button/button.component';

@Component({
  selector: 'app-root',
  imports: [ButtonComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  variants: ButtonVariant[] = ['primary', 'secondary', 'tertiary'];
}

<main style="padding: 32px; display: flex; flex-direction: column; gap: 24px;">
  <h1>web-ds Button — Angular pilot</h1>

  <section style="display: flex; gap: 16px; align-items: center;">
    @for (variant of variants; track variant) {
      <ds-button [variant]="variant">{{ variant }}</ds-button>
    }
  </section>

  <section style="display: flex; gap: 16px; align-items: center;">
    <ds-button variant="primary" size="sm">Small</ds-button>
    <ds-button variant="primary" size="md">Medium</ds-button>
    <ds-button variant="primary" size="lg">Large</ds-button>
  </section>

  <section style="display: flex; gap: 16px; align-items: center;">
    <ds-button variant="primary" shape="rounded">Rounded</ds-button>
    <ds-button variant="primary" [disabled]="true">Disabled</ds-button>
  </section>

  <section style="display: flex; gap: 16px; align-items: center; background: #1b1b1b; padding: 16px; border-radius: 8px;">
    <ds-button variant="primary" [inverse]="true">Inverse primary</ds-button>
    <ds-button variant="secondary" [inverse]="true">Inverse secondary</ds-button>
    <ds-button variant="tertiary" [inverse]="true">Inverse tertiary</ds-button>
  </section>
</main>
